services:
  rallly_db:
    image: postgres:14.2
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rallly:
    image: lukevella/rallly:latest
    restart: always
    depends_on:
      - rallly_db
    ports:
      - 3000:3000
    environment:
      # These environment variables will be passed through from the current shell
      - DATABASE_URL=postgres://postgres:postgres@rallly_db/db
      - SECRET_PASSWORD
      - NEXT_PUBLIC_BASE_URL
      - ALLOWED_EMAILS
      - NOREPLY_EMAIL
      - SUPPORT_EMAIL
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_SECURE
      - SMTP_USER
      - SMTP_PWD

volumes:
  db-data:
    driver: local
